[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true

# SPA rewrite rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200