[build]
  command = "cd Todo && npm install && npm run build"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200